apiVersion: v1
kind: Secret
metadata:
  name: serverless-secrets
  namespace: serverless
  labels:
    app.kubernetes.io/part-of: serverless-platform
type: Opaque
stringData:
  POSTGRES_USER: "serverless"
  POSTGRES_PASSWORD: "serverless123"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"
